// ── AFTER HOURS — CARD DATA ──
// Edit prompts and answers here.
// Name tokens: {p1} and {p2} are replaced with the players' actual names at runtime.
// Mood tags: "fun" | "deep" | "spicy" | "mix"

var PROMPTS = [
  // fun — some prompts use {p1} and {p2} which are replaced with player names at runtime
  { mood:"fun", en:"If {p1} and {p2} got stranded at an airport for 6 hours, it would definitely involve\u2026", sv:"Om {p1} och {p2} fastnade p\u00e5 en flygplats i 6 timmar skulle det definitivt involvera\u2026" },
  { mood:"fun", en:"The most ridiculous thing {p1} and {p2} have ever argued about is\u2026", sv:"Det mest absurda {p1} och {p2} n\u00e5gonsin br\u00e5kat om \u00e4r\u2026" },
  { mood:"fun", en:"If a reality show filmed us for a week, the highlight reel would include\u2026", sv:"Om ett reality-program filmade oss en vecka skulle h\u00f6jdpunkterna inkludera\u2026" },
  { mood:"fun", en:"Our perfect terrible night in always involves\u2026", sv:"V\u00e5r perfekta hemmakvalls-katastrof involverar alltid\u2026" },
  { mood:"fun", en:"If {p1} and {p2} had to survive a week in the wilderness, we\u2019d fail because of\u2026", sv:"Om {p1} och {p2} beh\u00f6vde \u00f6verleva en vecka i vildmarken skulle vi misslyckas p\u00e5 grund av\u2026" },
  { mood:"fun", en:"The most chaotic thing about us as a couple is\u2026", sv:"Det mest kaotiska med oss som par \u00e4r\u2026" },
  { mood:"fun", en:"We\u2019d never survive a cooking show because of\u2026", sv:"Vi skulle aldrig \u00f6verleva ett matlagningsprogram p\u00e5 grund av\u2026" },
  { mood:"fun", en:"What makes our neighbors slightly suspicious is probably\u2026", sv:"Det som f\u00e5r v\u00e5ra grannar att bli misst\u00e4nksamma \u00e4r f\u00f6rmodligen\u2026" },
  { mood:"fun", en:"On our last trip, things went sideways because of\u2026", sv:"P\u00e5 v\u00e5r senaste resa sp\u00e5rade det ur p\u00e5 grund av\u2026" },
  { mood:"fun", en:"If someone followed {p1} and {p2} around for a day, the weirdest part would be\u2026", sv:"Om n\u00e5gon f\u00f6ljde {p1} och {p2} under en dag skulle det konstiga vara\u2026" },
  // deep
  { mood:"deep", en:"If {p1} and {p2} wrote a book together, the first chapter would be called\u2026", sv:"Om {p1} och {p2} skrev en bok tillsammans skulle f\u00f6rsta kapitlet heta\u2026" },
  { mood:"deep", en:"Our love language, if we\u2019re being truly honest, is\u2026", sv:"V\u00e5rt k\u00e4rleksspr\u00e5k, om vi \u00e4r helt \u00e4rliga, \u00e4r\u2026" },
  { mood:"deep", en:"If we made a documentary about this relationship, the tagline would be\u2026", sv:"Om vi gjorde en dokument\u00e4r om det h\u00e4r f\u00f6rh\u00e5llandet skulle taglinjen vara\u2026" },
  { mood:"deep", en:"If we had a couple\u2019s theme song, it would be about\u2026", sv:"Om vi hade en gemensam temal\u00e5t skulle den handla om\u2026" },
  { mood:"deep", en:"The most honest thing I could say about our morning routine is\u2026", sv:"Det mest \u00e4rliga jag kan s\u00e4ga om v\u00e5r morgonrutin \u00e4r\u2026" },
  { mood:"deep", en:"If we explained our relationship to a therapist, we\u2019d start with\u2026", sv:"Om vi f\u00f6rklarade v\u00e5r relation f\u00f6r en terapeut skulle vi b\u00f6rja med\u2026" },
  { mood:"deep", en:"The thing about {p1} and {p2} that I think will still be true in ten years is\u2026", sv:"Det med {p1} och {p2} som jag tror fortfarande st\u00e4mmer om tio \u00e5r \u00e4r\u2026" },
  { mood:"deep", en:"The thing I noticed about {p2} first that I\u2019ve never said out loud is\u2026", sv:"Det jag m\u00e4rkte hos {p2} f\u00f6rst som jag aldrig sagt h\u00f6gt \u00e4r\u2026" },
  { mood:"deep", en:"If {p1} had to describe what makes us work in one sentence, they\u2019d say\u2026", sv:"Om {p1} med en mening skulle beskriva vad som g\u00f6r att vi fungerar, skulle de s\u00e4ga\u2026" },
  // spicy
  { mood:"spicy", en:"If {p1} and {p2} had a whole evening with no plans and no phones, it would definitely involve\u2026", sv:"Om {p1} och {p2} hade en hel kv\u00e4ll utan planer och utan telefoner skulle det definitivt involvera\u2026" },
  { mood:"spicy", en:"The thing {p1} does that {p2} finds impossible to resist is\u2026", sv:"Det som {p1} g\u00f6r som {p2} om\u00f6jligt kan mots\u00e5 \u00e4r\u2026" },
  { mood:"spicy", en:"The most unexpectedly good night {p1} and {p2} had together always started with\u2026", sv:"Den mest ov\u00e4ntat bra kv\u00e4llen {p1} och {p2} haft tillsammans b\u00f6rjade alltid med\u2026" },
  { mood:"spicy", en:"If {p1} and {p2} checked into a hotel right now with zero agenda, the first thing would be\u2026", sv:"Om {p1} och {p2} checkade in p\u00e5 ett hotell just nu utan plan, det f\u00f6rsta som skulle h\u00e4nda \u00e4r\u2026" },
  { mood:"spicy", en:"The thing {p1} and {p2} both think about more than they admit is\u2026", sv:"Det {p1} och {p2} b\u00e5da t\u00e4nker p\u00e5 mer \u00e4n de erk\u00e4nner \u00e4r\u2026" },
  { mood:"spicy", en:"The version of {p1} and {p2} that I like most always involves\u2026", sv:"Den version av {p1} och {p2} som jag gillar mest involverar alltid\u2026" }
];

var ANSWERS = [
  // fun — some cards use {p1} and {p2} which are replaced with player names at runtime
  { mood:"fun", en:"{p2} refusing to pick a restaurant", sv:"{p2} v\u00e4grar v\u00e4lja restaurang" },
  { mood:"fun", en:"completely lost, very confident", sv:"helt vilse, v\u00e4ldigt s\u00e4kra" },
  { mood:"fun", en:"strong opinions, wrong topics", sv:"starka \u00e5sikter, fel \u00e4mnen" },
  { mood:"fun", en:"zero plan, full confidence", sv:"ingen plan, full tilltro" },
  { mood:"fun", en:"lost and calling it a detour", sv:"vilse och kallar det omv\u00e4g" },
  { mood:"fun", en:"the thermostat, again", sv:"termostaten, igen" },
  { mood:"fun", en:"google maps open, still wrong", sv:"google maps \u00f6ppen, \u00e4nd\u00e5 fel" },
  { mood:"fun", en:"a bad idea we both loved", sv:"en d\u00e5lig id\u00e9 vi b\u00e5da \u00e4lskade" },
  { mood:"fun", en:"a snack run that became plans", sv:"ett mellanm\u00e5lsbrott som blev planer" },
  { mood:"fun", en:"picking a movie for three hours", sv:"v\u00e4lja film i tre timmar" },
  { mood:"fun", en:"a terrible idea, unanimous vote", sv:"en usel id\u00e9, enh\u00e4lligt beslut" },
  { mood:"fun", en:"{p1} having a dramatic reaction to something tiny", sv:"{p1} reagerar dramatiskt p\u00e5 n\u00e5got litet" },
  { mood:"fun", en:"{p1} turning it into a competition", sv:"{p1} g\u00f6r det till en t\u00e4vling" },
  { mood:"fun", en:"fake confidence, wrong direction", sv:"fejkat sj\u00e4lvf\u00f6rtroende, fel riktning" },
  { mood:"fun", en:"{p2} buying it anyway, obviously", sv:"{p2} k\u00f6per det \u00e4nd\u00e5, sj\u00e4lvklart" },
  { mood:"fun", en:"arguing loudly about nothing", sv:"br\u00e5ka h\u00f6gljutt om ingenting" },
  { mood:"fun", en:"{p1} being late, as always", sv:"{p1} som \u00e4r sen, som alltid" },
  { mood:"fun", en:"making it up as we go", sv:"improvisera allt eftersom" },
  { mood:"fun", en:"{p2} being right, forever and always", sv:"{p2} som har r\u00e4tt, f\u00f6r alltid och evigt" },
  { mood:"fun", en:"the food decision spiral", sv:"mat-beslutsspiralen" },
  { mood:"fun", en:"the \u2018this is fine\u2019 look", sv:"den d\u00e4r \u2018allt \u00e4r bra\u2019-blicken" },
  { mood:"fun", en:"somehow involving a lot of food", sv:"mat inblandad p\u00e5 n\u00e5got s\u00e4tt" },
  { mood:"fun", en:"a debate nobody asked for", sv:"en debatt ingen bad om" },
  { mood:"fun", en:"eternal optimism, zero evidence", sv:"evig optimism, noll bevis" },
  { mood:"fun", en:"the nap that cancelled everything", sv:"tuppluren som st\u00e4llde in allt" },
  // deep
  { mood:"deep", en:"growing in the same direction", sv:"v\u00e4xa \u00e5t samma h\u00e5ll" },
  { mood:"deep", en:"only existing around you", sv:"bara finns n\u00e4r du \u00e4r h\u00e4r" },
  { mood:"deep", en:"a comfortable silence", sv:"en bekv\u00e4m tystnad" },
  { mood:"deep", en:"the thing you already know", sv:"det du redan vet" },
  { mood:"deep", en:"easier than it used to be", sv:"l\u00e4ttare \u00e4n det var f\u00f6rut" },
  { mood:"deep", en:"the ritual nobody chose", sv:"ritualen ingen best\u00e4mde" },
  { mood:"deep", en:"the way you actually laugh", sv:"s\u00e4ttet du verkligen skrattar p\u00e5" },
  { mood:"deep", en:"dropping the impressive act", sv:"sluta f\u00f6rs\u00f6ka imponera" },
  { mood:"deep", en:"a memory only we get", sv:"ett minne bara vi f\u00f6rst\u00e5r" },
  { mood:"deep", en:"a fear only you know", sv:"en r\u00e4dsla bara du vet" },
  { mood:"deep", en:"the story we don\u2019t tell", sv:"storyn vi inte ber\u00e4ttar" },
  { mood:"deep", en:"a conversation we never finished", sv:"ett samtal vi aldrig avslutade" },
  { mood:"deep", en:"different in ways that work", sv:"olika p\u00e5 s\u00e4tt som funkar" },
  { mood:"deep", en:"less scared since you showed up", sv:"mindre r\u00e4dd sedan du d\u00f6k upp" },
  { mood:"deep", en:"still figuring this part out", sv:"fortfarande inte fattat den biten" },
  { mood:"deep", en:"no words for it yet", sv:"inga ord f\u00f6r det \u00e4n" },
  { mood:"deep", en:"a fight that made things better", sv:"ett br\u00e5k som f\u00f6rb\u00e4ttrade saker" },
  { mood:"deep", en:"the thing that stays the same", sv:"det som f\u00f6rblir detsamma" },
  // spicy
  { mood:"spicy", en:"absolutely nowhere to be", sv:"absolut ingenstans att vara" },
  { mood:"spicy", en:"that look. you know the one.", sv:"den blicken. du vet vilken." },
  { mood:"spicy", en:"knowing exactly where it was going", sv:"precis visste vart det ledde" },
  { mood:"spicy", en:"zero plans, zero guilt", sv:"noll planer, noll skuld" },
  { mood:"spicy", en:"both saying yes before asking", sv:"b\u00e5da sa ja innan vi fr\u00e5gade" },
  { mood:"spicy", en:"a very deliberate outfit choice", sv:"ett v\u00e4ldigt medvetet kl\u00e4dval" },
  { mood:"spicy", en:"stopping talking on purpose", sv:"sluta prata med flit" },
  { mood:"spicy", en:"blaming it on being tired", sv:"skylla p\u00e5 att vi var tr\u00f6tta" },
  { mood:"spicy", en:"a good decision at midnight", sv:"ett bra beslut vid midnatt" },
  { mood:"spicy", en:"phones off, nobody warned", sv:"telefoner av, ingen varnad" },
  { mood:"spicy", en:"hotel room, no agenda", sv:"hotellrum, ingen agenda" },
  { mood:"spicy", en:"us, but nobody\u2019s watching", sv:"vi, men ingen tittar" },
  { mood:"spicy", en:"forgetting what we argued about", sv:"gl\u00f6mma vad vi br\u00e5kade om" },
  { mood:"spicy", en:"the agreed-upon distraction", sv:"den \u00f6verenskomna distraktionen" },
  { mood:"spicy", en:"one thing leading to everything", sv:"en sak som ledde till allt" },
  { mood:"spicy", en:"staying in and meaning it", sv:"stanna hemma och mena det" },
  { mood:"spicy", en:"finally saying the thing", sv:"\u00e4ntligen s\u00e4ga grejen" },
  // mix — works for any mood
  { mood:"mix", en:"the look that said everything", sv:"blicken som sa allt" },
  { mood:"mix", en:"this was the plan, actually", sv:"det h\u00e4r var planen, faktiskt" },
  { mood:"mix", en:"a snack that fixed everything", sv:"ett mellanm\u00e5l som fixade allt" },
  { mood:"mix", en:"our specific kind of chaos", sv:"v\u00e5rt specifika slags kaos" },
  { mood:"mix", en:"same thought, same second", sv:"samma tanke, samma sekund" },
  { mood:"mix", en:"completely unplanned, somehow great", sv:"helt oplanerat, \u00e4nd\u00e5 bra" },
  { mood:"mix", en:"full selves, no filter", sv:"hela oss, inget filter" },
  { mood:"mix", en:"something that became our thing", sv:"n\u00e5got som blev v\u00e5r grej" },
  { mood:"mix", en:"weirdly great time anyway", sv:"konstigt bra kv\u00e4ll \u00e4nd\u00e5" },
  { mood:"mix", en:"being right, very quietly", sv:"ha r\u00e4tt, v\u00e4ldigt tyst" },
  { mood:"mix", en:"looking at each other and laughing", sv:"titta p\u00e5 varandra och skratta" },
  { mood:"mix", en:"choosing us over the plan", sv:"v\u00e4lja oss \u00f6ver planen" }
];
