// ── AFTER HOURS — CARD DATA ──
// Edit prompts and answers here.
// Name tokens: {p1} and {p2} are replaced with the players' actual names at runtime.
// Mood tags: "fun" | "deep" | "spicy" | "mix"

var PROMPTS = [
  // fun — some prompts use {p1} and {p2} which are replaced with player names at runtime
  { mood:"fun", en:"If {p1} and {p2} got stranded at an airport for 6 hours, it would definitely involve\u2026", sv:"Om {p1} och {p2} fastnade p\u00e5 en flygplats i 6 timmar skulle det definitivt involvera\u2026" },
  { mood:"fun", en:"The most ridiculous thing {p1} and {p2} have ever argued about is\u2026", sv:"Det mest absurda {p1} och {p2} n\u00e5gonsin br\u00e5kat om \u00e4r\u2026" },
  { mood:"fun", en:"If a reality show filmed us for a week, the highlight reel would include\u2026", sv:"Om ett reality-program filmade oss en vecka skulle h\u00f6jdpunkterna inkludera\u2026" },
  { mood:"fun", en:"Our perfect terrible night in always involves\u2026", sv:"V\u00e5r perfekta hemmakvalls-katastrof involverar alltid\u2026" },
  { mood:"fun", en:"If {p1} and {p2} had to survive a week in the wilderness, we\u2019d fail because of\u2026", sv:"Om {p1} och {p2} beh\u00f6vde \u00f6verleva en vecka i vildmarken skulle vi misslyckas p\u00e5 grund av\u2026" },
  { mood:"fun", en:"The most chaotic thing about us as a couple is\u2026", sv:"Det mest kaotiska med oss som par \u00e4r\u2026" },
  { mood:"fun", en:"We\u2019d never survive a cooking show because of\u2026", sv:"Vi skulle aldrig \u00f6verleva ett matlagningsprogram p\u00e5 grund av\u2026" },
  { mood:"fun", en:"What makes our neighbors slightly suspicious is probably\u2026", sv:"Det som f\u00e5r v\u00e5ra grannar att bli misst\u00e4nksamma \u00e4r f\u00f6rmodligen\u2026" },
  { mood:"fun", en:"On our last trip, things went sideways because of\u2026", sv:"P\u00e5 v\u00e5r senaste resa sp\u00e5rade det ur p\u00e5 grund av\u2026" },
  { mood:"fun", en:"If someone followed {p1} and {p2} around for a day, the weirdest part would be\u2026", sv:"Om n\u00e5gon f\u00f6ljde {p1} och {p2} under en dag skulle det konstiga vara\u2026" },
  // deep
  { mood:"deep", en:"If {p1} and {p2} wrote a book together, the first chapter would be called\u2026", sv:"Om {p1} och {p2} skrev en bok tillsammans skulle f\u00f6rsta kapitlet heta\u2026" },
  { mood:"deep", en:"Our love language, if we\u2019re being truly honest, is\u2026", sv:"V\u00e5rt k\u00e4rleksspr\u00e5k, om vi \u00e4r helt \u00e4rliga, \u00e4r\u2026" },
  { mood:"deep", en:"If we made a documentary about this relationship, the tagline would be\u2026", sv:"Om vi gjorde en dokument\u00e4r om det h\u00e4r f\u00f6rh\u00e5llandet skulle taglinjen vara\u2026" },
  { mood:"deep", en:"If we had a couple\u2019s theme song, it would be about\u2026", sv:"Om vi hade en gemensam temal\u00e5t skulle den handla om\u2026" },
  { mood:"deep", en:"The most honest thing I could say about our morning routine is\u2026", sv:"Det mest \u00e4rliga jag kan s\u00e4ga om v\u00e5r morgonrutin \u00e4r\u2026" },
  { mood:"deep", en:"If we explained our relationship to a therapist, we\u2019d start with\u2026", sv:"Om vi f\u00f6rklarade v\u00e5r relation f\u00f6r en terapeut skulle vi b\u00f6rja med\u2026" },
  { mood:"deep", en:"The thing about {p1} and {p2} that I think will still be true in ten years is\u2026", sv:"Det med {p1} och {p2} som jag tror fortfarande st\u00e4mmer om tio \u00e5r \u00e4r\u2026" },
  { mood:"deep", en:"The thing I noticed about {p2} first that I\u2019ve never said out loud is\u2026", sv:"Det jag m\u00e4rkte hos {p2} f\u00f6rst som jag aldrig sagt h\u00f6gt \u00e4r\u2026" },
  { mood:"deep", en:"If {p1} had to describe what makes us work in one sentence, they\u2019d say\u2026", sv:"Om {p1} med en mening skulle beskriva vad som g\u00f6r att vi fungerar, skulle de s\u00e4ga\u2026" },
  // spicy
  { mood:"spicy", en:"If {p1} and {p2} had a whole evening with no plans and no phones, it would definitely involve\u2026", sv:"Om {p1} och {p2} hade en hel kv\u00e4ll utan planer och utan telefoner skulle det definitivt involvera\u2026" },
  { mood:"spicy", en:"The thing {p1} does that {p2} finds impossible to resist is\u2026", sv:"Det som {p1} g\u00f6r som {p2} om\u00f6jligt kan mots\u00e5 \u00e4r\u2026" },
  { mood:"spicy", en:"The most unexpectedly good night {p1} and {p2} had together always started with\u2026", sv:"Den mest ov\u00e4ntat bra kv\u00e4llen {p1} och {p2} haft tillsammans b\u00f6rjade alltid med\u2026" },
  { mood:"spicy", en:"If {p1} and {p2} checked into a hotel right now with zero agenda, the first thing would be\u2026", sv:"Om {p1} och {p2} checkade in p\u00e5 ett hotell just nu utan plan, det f\u00f6rsta som skulle h\u00e4nda \u00e4r\u2026" },
  { mood:"spicy", en:"The thing {p1} and {p2} both think about more than they admit is\u2026", sv:"Det {p1} och {p2} b\u00e5da t\u00e4nker p\u00e5 mer \u00e4n de erk\u00e4nner \u00e4r\u2026" },
  { mood:"spicy", en:"The version of {p1} and {p2} that I like most always involves\u2026", sv:"Den version av {p1} och {p2} som jag gillar mest involverar alltid\u2026" }
];

var ANSWERS = [
  // fun — concrete, visual, relatable couple moments
  { mood:"fun", en:"{p2} refusing to pick a restaurant", sv:"{p2} v\u00e4grar v\u00e4lja restaurang" },
  { mood:"fun", en:"one of us googling it mid-fight", sv:"en av oss googlar mitt i br\u00e5ket" },
  { mood:"fun", en:"a shopping cart full of snacks", sv:"en kundvagn full med snacks" },
  { mood:"fun", en:"passive-aggressive IKEA assembly", sv:"passiv-aggressivt IKEA-bygge" },
  { mood:"fun", en:"{p1} saying \u2018I told you so\u2019", sv:"{p1} som s\u00e4ger \u2018vad sa jag\u2019" },
  { mood:"fun", en:"the thermostat war", sv:"termostat-kriget" },
  { mood:"fun", en:"a three-hour movie debate", sv:"en tre timmar l\u00e5ng filmdebatt" },
  { mood:"fun", en:"drunk online shopping at 1am", sv:"fylleshoppande online klockan ett" },
  { mood:"fun", en:"a nap that ruined all plans", sv:"en tupplur som f\u00f6rst\u00f6rde alla planer" },
  { mood:"fun", en:"ordering food twice in one night", sv:"best\u00e4lla mat tv\u00e5 g\u00e5nger p\u00e5 en kv\u00e4ll" },
  { mood:"fun", en:"a very loud wrong opinion", sv:"en v\u00e4ldigt h\u00f6gljudd fel \u00e5sikt" },
  { mood:"fun", en:"{p1} dramatically reading the receipt", sv:"{p1} som dramatiskt l\u00e4ser kvittot" },
  { mood:"fun", en:"{p1} turning everything into a race", sv:"{p1} som g\u00f6r allt till en t\u00e4vling" },
  { mood:"fun", en:"both blaming the GPS", sv:"b\u00e5da skyller p\u00e5 GPS:en" },
  { mood:"fun", en:"{p2} buying it and hiding the bag", sv:"{p2} k\u00f6per det och g\u00f6mmer p\u00e5sen" },
  { mood:"fun", en:"a parking lot argument", sv:"ett parkeringsplatsbr\u00e5k" },
  { mood:"fun", en:"{p1} being 20 minutes late, again", sv:"{p1} som \u00e4r 20 minuter sen, igen" },
  { mood:"fun", en:"wine on a Tuesday for no reason", sv:"vin p\u00e5 en tisdag utan anledning" },
  { mood:"fun", en:"{p2} pretending not to be hangry", sv:"{p2} som l\u00e5tsas inte vara hungrig-arg" },
  { mood:"fun", en:"an IKEA trip that tested us", sv:"ett IKEA-bes\u00f6k som testade oss" },
  { mood:"fun", en:"one blanket and zero compromise", sv:"en filt och noll kompromisser" },
  { mood:"fun", en:"a grocery list that went off the rails", sv:"en inhandlingslista som sp\u00e5rade ur" },
  { mood:"fun", en:"accidental matching outfits", sv:"oavsiktligt matchande kl\u00e4der" },
  { mood:"fun", en:"someone\u2019s \u2018shortcut\u2019 adding 40 minutes", sv:"n\u00e5gons \u2018genv\u00e4g\u2019 som la till 40 min" },
  { mood:"fun", en:"a shared dessert and a silent power struggle", sv:"en delad dessert och en tyst maktkamp" },
  // deep
  { mood:"deep", en:"learning to fight better", sv:"l\u00e4ra sig br\u00e5ka b\u00e4ttre" },
  { mood:"deep", en:"the version of me only you see", sv:"versionen av mig bara du ser" },
  { mood:"deep", en:"a silence that actually felt safe", sv:"en tystnad som k\u00e4ndes trygg" },
  { mood:"deep", en:"knowing without having to ask", sv:"veta utan att beh\u00f6va fr\u00e5ga" },
  { mood:"deep", en:"choosing each other on the hard days", sv:"v\u00e4lja varandra p\u00e5 tunga dagar" },
  { mood:"deep", en:"the Sunday routine nobody planned", sv:"s\u00f6ndagsrutinen ingen planerade" },
  { mood:"deep", en:"your real laugh, not the polite one", sv:"ditt riktiga skratt, inte det artiga" },
  { mood:"deep", en:"letting {p2} see the ugly cry", sv:"l\u00e5ta {p2} se fulb\u00f6let" },
  { mood:"deep", en:"the 2am conversation that changed things", sv:"samtalet klockan tv\u00e5 som f\u00f6r\u00e4ndrade allt" },
  { mood:"deep", en:"a fear I only told you", sv:"en r\u00e4dsla jag bara ber\u00e4ttade f\u00f6r dig" },
  { mood:"deep", en:"the fight we needed to have", sv:"br\u00e5ket vi beh\u00f6vde ha" },
  { mood:"deep", en:"a promise that didn\u2019t need words", sv:"ett l\u00f6fte som inte beh\u00f6vde ord" },
  { mood:"deep", en:"being weird in the exact same way", sv:"vara konstiga p\u00e5 exakt samma s\u00e4tt" },
  { mood:"deep", en:"feeling at home in the car together", sv:"k\u00e4nna sig hemma i bilen ihop" },
  { mood:"deep", en:"admitting I was wrong (finally)", sv:"erk\u00e4nna att jag hade fel (till slut)" },
  { mood:"deep", en:"the inside joke nobody else gets", sv:"internsk\u00e4mtet ingen annan fattar" },
  { mood:"deep", en:"forgiving faster than expected", sv:"f\u00f6rl\u00e5ta snabbare \u00e4n v\u00e4ntat" },
  { mood:"deep", en:"holding hands and saying nothing", sv:"h\u00e5lla h\u00e4nder och inte s\u00e4ga n\u00e5got" },
  // spicy
  { mood:"spicy", en:"a locked door and zero agenda", sv:"en l\u00e5st d\u00f6rr och noll agenda" },
  { mood:"spicy", en:"that look across the dinner table", sv:"den d\u00e4r blicken \u00f6ver middagsbordet" },
  { mood:"spicy", en:"whispering something very inappropriate", sv:"viska n\u00e5got v\u00e4ldigt ol\u00e4mpligt" },
  { mood:"spicy", en:"cancelling plans and not being sorry", sv:"st\u00e4lla in planer utan \u00e5nger" },
  { mood:"spicy", en:"a dare nobody backed down from", sv:"en utmaning ingen backade fr\u00e5n" },
  { mood:"spicy", en:"{p1} wearing that outfit on purpose", sv:"{p1} som bar den kl\u00e4dseln med flit" },
  { mood:"spicy", en:"a very long shower for two", sv:"en v\u00e4ldigt l\u00e5ng dusch f\u00f6r tv\u00e5" },
  { mood:"spicy", en:"blaming it on the wine", sv:"skylla p\u00e5 vinet" },
  { mood:"spicy", en:"a hotel room and room service", sv:"ett hotellrum och rums\u00e4rvice" },
  { mood:"spicy", en:"the text that started everything", sv:"meddelandet som startade allt" },
  { mood:"spicy", en:"phones off, door locked", sv:"telefoner av, d\u00f6rren l\u00e5st" },
  { mood:"spicy", en:"{p2} biting their lip like that", sv:"{p2} som biter sig i l\u00e4ppen s\u00e5 d\u00e4r" },
  { mood:"spicy", en:"making up after the argument", sv:"f\u00f6rsoningen efter br\u00e5ket" },
  { mood:"spicy", en:"a playlist and a very late night", sv:"en spellista och en v\u00e4ldigt sen kv\u00e4ll" },
  { mood:"spicy", en:"an innocent massage that wasn\u2019t", sv:"en oskyldig massage som inte var det" },
  { mood:"spicy", en:"staying in bed until embarrassingly late", sv:"stanna i s\u00e4ngen pinsamt l\u00e4nge" },
  { mood:"spicy", en:"saying \u2018one more\u2019 and meaning it", sv:"s\u00e4ga \u2018en till\u2019 och mena det" },
  // mix — works for any mood
  { mood:"mix", en:"a shared look that said everything", sv:"en blick som sa allt" },
  { mood:"mix", en:"cheese and wine at 11pm", sv:"ost och vin klockan 23" },
  { mood:"mix", en:"both thinking the same thing", sv:"b\u00e5da t\u00e4nker samma sak" },
  { mood:"mix", en:"our weird little ritual", sv:"v\u00e5r konstiga lilla ritual" },
  { mood:"mix", en:"a road trip playlist argument", sv:"ett br\u00e5k om bilspellistan" },
  { mood:"mix", en:"one of us caving first", sv:"en av oss som ger efter f\u00f6rst" },
  { mood:"mix", en:"a takeaway on the kitchen floor", sv:"takeaway p\u00e5 k\u00f6ksgolvet" },
  { mood:"mix", en:"laughing so hard we couldn\u2019t stop", sv:"skratta s\u00e5 vi inte kunde sluta" },
  { mood:"mix", en:"a secret we\u2019ll never tell anyone", sv:"en hemlighet vi aldrig ber\u00e4ttar" },
  { mood:"mix", en:"the couch, a blanket, and zero words", sv:"soffan, en filt, och noll ord" },
  { mood:"mix", en:"being embarrassing together in public", sv:"vara pinsamma ihop offentligt" },
  { mood:"mix", en:"a plan that went perfectly wrong", sv:"en plan som gick perfekt fel" }
];
